import {
  Book,
  Waveform,
  MusicNotesSimple,
  AirplaneTilt,
  PawPrint,
  Barbell,
  Heartbeat,
  Article,
  BabyCarriage,
  Brain,
  Bread,
  Briefcase,
  Camera,
  Campfire,
  ChefHat,
  City,
  Cloud,
  Club,
  Code,
  Cpu,
  Cube,
  Eyeglasses,
  FilmSlate,
  Globe,
  Grains,
  HouseLine,
  Layout,
  Lego,
  Martini,
  Money,
  Network,
  PaintBrush,
  PenNibStraight,
  Planet,
  PottedPlant,
  Sailboat,
  Television,
  TShirt,
  Users,
} from "@phosphor-icons/react";

export const icons = [
  { name: "book", icon: Book },
  { name: "waveform", icon: Waveform },
  { name: "musicNotesSimple", icon: MusicNotesSimple },
  { name: "airplaneTilt", icon: AirplaneTilt },
  { name: "pawPrint", icon: PawPrint },
  { name: "barbell", icon: Barbell },
  { name: "heartbeat", icon: Heartbeat },
  { name: "paintBrush", icon: PaintBrush },
  { name: "money", icon: Money },
  { name: "code", icon: Code },
  { name: "cloud", icon: Cloud },
  { name: "houseLine", icon: HouseLine },
  { name: "cube", icon: Cube },
  { name: "campfire", icon: Campfire },
  { name: "club", icon: Club },
  { name: "planet", icon: Planet },
  { name: "network", icon: Network },
  { name: "filmSlate", icon: FilmSlate },
  { name: "martini", icon: Martini },
  { name: "chefHat", icon: ChefHat },
  { name: "sailboat", icon: Sailboat },
  { name: "bread", icon: Bread },
  { name: "pottedPlant", icon: PottedPlant },
  { name: "penNibStraight", icon: PenNibStraight },
  { name: "lego", icon: Lego },
  { name: "briefcase", icon: Briefcase },
  { name: "eyeglasses", icon: Eyeglasses },
  { name: "tShirt", icon: TShirt },
  { name: "globe", icon: Globe },
  { name: "camera", icon: Camera },
  { name: "television", icon: Television },
  { name: "layout", icon: Layout },
  { name: "cpu", icon: Cpu },
  { name: "city", icon: City },
  { name: "grains", icon: Grains },
  { name: "users", icon: Users },
  { name: "babyCarriage", icon: BabyCarriage },
  { name: "brain", icon: Brain },
  { name: "article", icon: Article },
];
