import type { Colour } from "./Colour.type";

export const colours: { [key: string]: Colour } = {
  red: {
    name: "red",
    text: "text-red-400",
    textPill: "text-red-500",
    textPillInverted: "hover:text-red-600",
    background: "bg-red-400",
    backgroundPill: "bg-red-100",
    backgroundPillInverted: "hover:bg-red-300",
    backgroundGlow: "hover:bg-red-50",
  },
  orange: {
    name: "orange",
    text: "text-orange-400",
    textPill: "text-orange-500",
    textPillInverted: "hover:text-orange-600",
    background: "bg-orange-400",
    backgroundPill: "bg-orange-100",
    backgroundPillInverted: "hover:bg-orange-300",
    backgroundGlow: "hover:bg-orange-50",
  },
  yellow: {
    name: "yellow",
    text: "text-yellow-400",
    textPill: "text-yellow-500",
    textPillInverted: "hover:text-yellow-600",
    background: "bg-yellow-400",
    backgroundPill: "bg-yellow-100",
    backgroundPillInverted: "hover:bg-yellow-300",
    backgroundGlow: "hover:bg-yellow-50",
  },
  lime: {
    name: "lime",
    text: "text-lime-400",
    textPill: "text-lime-500",
    textPillInverted: "hover:text-lime-600",
    background: "bg-lime-400",
    backgroundPill: "bg-lime-100",
    backgroundPillInverted: "hover:bg-lime-300",
    backgroundGlow: "hover:bg-lime-50",
  },
  green: {
    name: "green",
    text: "text-green-400",
    textPill: "text-green-500",
    textPillInverted: "hover:text-green-600",
    background: "bg-green-400",
    backgroundPill: "bg-green-100",
    backgroundPillInverted: "hover:bg-green-300",
    backgroundGlow: "hover:bg-green-50",
  },
  blue: {
    name: "blue",
    text: "text-blue-400",
    textPill: "text-blue-500",
    textPillInverted: "hover:text-blue-600",
    background: "bg-blue-400",
    backgroundPill: "bg-blue-100",
    backgroundPillInverted: "hover:bg-blue-300",
    backgroundGlow: "hover:bg-blue-50",
  },
  cyan: {
    name: "cyan",
    text: "text-cyan-400",
    textPill: "text-cyan-500",
    textPillInverted: "hover:text-cyan-600",
    background: "bg-cyan-400",
    backgroundPill: "bg-cyan-100",
    backgroundPillInverted: "hover:bg-cyan-300",
    backgroundGlow: "hover:bg-cyan-50",
  },
  pink: {
    name: "pink",
    text: "text-pink-400",
    textPill: "text-pink-500",
    textPillInverted: "hover:text-pink-600",
    background: "bg-pink-400",
    backgroundPill: "bg-pink-100",
    backgroundPillInverted: "hover:bg-pink-300",
    backgroundGlow: "hover:bg-pink-50",
  },
  purple: {
    name: "purple",
    text: "text-purple-400",
    textPill: "text-purple-500",
    textPillInverted: "hover:text-purple-600",
    background: "bg-purple-400",
    backgroundPill: "bg-purple-100",
    backgroundPillInverted: "hover:bg-purple-300",
    backgroundGlow: "hover:bg-purple-50",
  },
  brown: {
    name: "brown",
    text: "text-amber-600",
    textPill: "text-amber-700",
    textPillInverted: "hover:text-amber-600",
    background: "bg-amber-600",
    backgroundPill: "bg-amber-200",
    backgroundPillInverted: "hover:bg-amber-300",
    backgroundGlow: "hover:bg-amber-50",
  },
  grey: {
    name: "grey",
    text: "text-gray-400",
    textPill: "text-gray-500",
    textPillInverted: "hover:text-gray-600",
    background: "bg-gray-400",
    backgroundPill: "bg-gray-200",
    backgroundPillInverted: "hover:bg-gray-300",
    backgroundGlow: "hover:bg-gray-100",
  },
};
