services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./pb_data:/pb/pb_data"
      - "./pb_migrations:/pb/pb_migrations"
