/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StreamIndexImport } from './routes/stream/index'
import { Route as JournalsJournalIdIndexImport } from './routes/journals/$journalId/index'
import { Route as authenticationSignupIndexImport } from './routes/(authentication)/signup/index'
import { Route as authenticationLoginIndexImport } from './routes/(authentication)/login/index'

// Create/Update Routes

const StreamIndexRoute = StreamIndexImport.update({
  id: '/stream/',
  path: '/stream/',
  getParentRoute: () => rootRoute,
} as any)

const JournalsJournalIdIndexRoute = JournalsJournalIdIndexImport.update({
  id: '/journals/$journalId/',
  path: '/journals/$journalId/',
  getParentRoute: () => rootRoute,
} as any)

const authenticationSignupIndexRoute = authenticationSignupIndexImport.update({
  id: '/(authentication)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const authenticationLoginIndexRoute = authenticationLoginIndexImport.update({
  id: '/(authentication)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream/': {
      id: '/stream/'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamIndexImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/login/': {
      id: '/(authentication)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authenticationLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/signup/': {
      id: '/(authentication)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authenticationSignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/journals/$journalId/': {
      id: '/journals/$journalId/'
      path: '/journals/$journalId'
      fullPath: '/journals/$journalId'
      preLoaderRoute: typeof JournalsJournalIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/stream': typeof StreamIndexRoute
  '/login': typeof authenticationLoginIndexRoute
  '/signup': typeof authenticationSignupIndexRoute
  '/journals/$journalId': typeof JournalsJournalIdIndexRoute
}

export interface FileRoutesByTo {
  '/stream': typeof StreamIndexRoute
  '/login': typeof authenticationLoginIndexRoute
  '/signup': typeof authenticationSignupIndexRoute
  '/journals/$journalId': typeof JournalsJournalIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/stream/': typeof StreamIndexRoute
  '/(authentication)/login/': typeof authenticationLoginIndexRoute
  '/(authentication)/signup/': typeof authenticationSignupIndexRoute
  '/journals/$journalId/': typeof JournalsJournalIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stream' | '/login' | '/signup' | '/journals/$journalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/stream' | '/login' | '/signup' | '/journals/$journalId'
  id:
    | '__root__'
    | '/stream/'
    | '/(authentication)/login/'
    | '/(authentication)/signup/'
    | '/journals/$journalId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  StreamIndexRoute: typeof StreamIndexRoute
  authenticationLoginIndexRoute: typeof authenticationLoginIndexRoute
  authenticationSignupIndexRoute: typeof authenticationSignupIndexRoute
  JournalsJournalIdIndexRoute: typeof JournalsJournalIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  StreamIndexRoute: StreamIndexRoute,
  authenticationLoginIndexRoute: authenticationLoginIndexRoute,
  authenticationSignupIndexRoute: authenticationSignupIndexRoute,
  JournalsJournalIdIndexRoute: JournalsJournalIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/stream/",
        "/(authentication)/login/",
        "/(authentication)/signup/",
        "/journals/$journalId/"
      ]
    },
    "/stream/": {
      "filePath": "stream/index.tsx"
    },
    "/(authentication)/login/": {
      "filePath": "(authentication)/login/index.tsx"
    },
    "/(authentication)/signup/": {
      "filePath": "(authentication)/signup/index.tsx"
    },
    "/journals/$journalId/": {
      "filePath": "journals/$journalId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
